### ISSUE TITLE
demo is broken

### ISSUE THREAD

**Issue by arieller** [CleverProgrammers/tiktok-clone#1]
and also big thanks 👍

**Comment by Rohit544** [comment]
nice......😃😃😃

**Comment by haroldao** [comment]
yeah true...

**Comment by mehul523** [comment]
nice....

**Comment by kivasho** [comment]
true

**Comment by ghost** [comment]
yes :(

**Comment by saudkhan1391** [comment]
yeah, its not working

**Comment by ghost** [comment]
confirmed its not working. Its showing an issue in the console. :(

**Comment by githubsayan7776969** [comment]
no sir app works fine..u just need to use a vpn if tik tok is banned in ur nation
![Screenshot 2022-12-17 214143](https://user-images.githubusercontent.com/68245752/208251111-9809722e-a2da-4843-bffe-cde7ea535222.png)
